experiment_name: "simple3dcnn_adni_weighted_lr1e3"

data:
  spatial_size: [160, 190, 160]
  csv_path: "data/adni_nii_clean.csv"

model:
  num_classes: 3
  name: "Simple3DCNN"

training:
  seed: 42
  epochs: 50
  batch_size: 8
  num_workers: 4
  learning_rate: 0.001
  weight_decay: 0.0001
